DELETE http://localhost:3003/api/ballrooms/5ddd3f7122e3a387bf36de7a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbW8iLCJpZCI6IjVkZDkwOTQ4NjAzYWUwMTc5M2M4NTBmNiIsImlhdCI6MTU3NDUxMjIzMn0.fvB40iYXLyYeX3XA6FdFas5zn_HJd64SygD05DKI1z8