DELETE http://localhost:3003/api/ballrooms/5ddf9cb789af59255a8108dc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxhc3NlIiwiaWQiOiI1ZGRmOWQyMDBiNTk0NjI1N2YxZTY4NDIiLCJpYXQiOjE1NzQ5MzYyOTV9.vTNTP3Ap611mZydHbcXC3PH6RhxC6FrhtIDDXcY5JF0