DELETE http://localhost:3003/api/ballrooms/5dd90a94ec92a81846f87db5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpbW8iLCJpZCI6IjVkZDkwOTQ4NjAzYWUwMTc5M2M4NTBmNiIsImlhdCI6MTU3NDUxMjIzMn0.fvB40iYXLyYeX3XA6FdFas5zn_HJd64SygD05DKI1z8