POST http://localhost:3003/api/ballrooms/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxhc3NlIiwiaWQiOiI1ZTI4YjA3YjlhZDUyZDBhODgxMDRkZTUiLCJpYXQiOjE1Nzk3OTUzODR9.n3PL8UadjGxAxHJPBO4pUz9Gw9Tl44fLHEUw86V_HVk

{
	"title": "Pavi",
	"author": "simo",
	"url": "www://ruusulinna.fi"
}